name: Generate Datas

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  snk:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v0.0.18
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg

      - name: push github-snake.svg to the main branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
